name: alerta_fogo_new
description: Aplicativo de prevenção e resposta a incêndios.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^14.7.10
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  connectivity_plus: ^5.0.2
  http: ^0.13.6
  provider: ^6.1.1
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/